src/Entity/Cartes.php
<?php

namespace App\Entity;

use App\Repository\CartesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartesRepository::class)]
class Cartes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin_prevu = null;

    #[ORM\Column]
    private ?bool $cloture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fichier = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    /**
     * @var Collection<int, Users>
     */
    #[ORM\ManyToMany(targetEntity: Users::class, inversedBy: 'cartes')]
    private Collection $users;

    /**
     * @var Collection<int, Tags>
     */
    #[ORM\ManyToMany(targetEntity: Tags::class, inversedBy: 'cartes')]
    private Collection $tags;

    #[ORM\ManyToOne(inversedBy: 'cartes')]
    private ?Colonnes $colonnes = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getDateFinPrevu(): ?\DateTimeInterface
    {
        return $this->date_fin_prevu;
    }

    public function setDateFinPrevu(\DateTimeInterface $date_fin_prevu): static
    {
        $this->date_fin_prevu = $date_fin_prevu;

        return $this;
    }

    public function isCloture(): ?bool
    {
        return $this->cloture;
    }

    public function setCloture(bool $cloture): static
    {
        $this->cloture = $cloture;

        return $this;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(?string $fichier): static
    {
        $this->fichier = $fichier;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(Users $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Tags>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tags $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tags $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getColonnes(): ?Colonnes
    {
        return $this->colonnes;
    }

    public function setColonnes(?Colonnes $colonnes): static
    {
        $this->colonnes = $colonnes;

        return $this;
    }
}

src/Form/CartesType.php
<?php

namespace App\Form;

use App\Entity\Cartes;
use App\Entity\Colonnes;
use App\Entity\Tags;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CartesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-3 py-2 border border-gray-300 rounded-md'
                ],
            ])
            ->add('date_creation', null, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
                ]
            ])
            ->add('date_fin_prevu', null, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
                ]
            ])
            ->add('description', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-3 py-2 border border-gray-300 rounded-md'
                ]
            ])
            // ->add('users', EntityType::class, [
            //     'class' => Users::class,
            //     'choice_label' => 'prenom',
            //     'multiple' => true,
            // ])
            // ->add('tags', EntityType::class, [
            //     'class' => Tags::class,
            //     'choice_label' => 'id',
            //     'multiple' => true,
            // ])
            ->add('colonnes', EntityType::class, [
                'class' => Colonnes::class,
                'choice_label' => 'titre',
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Créer cartes',
                'attr' => [
                    'id' => 'submit-button',
                    'class' => 'px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cartes::class,
            'method' => 'POST',
            'attr' => [
                'id' => 'taskForm',
            ],
        ]);
    }
}

src/Controller/CartesController.php
<?php

namespace App\Controller;

use App\Entity\Cartes;
use App\Form\CartesType;
use App\Repository\CartesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/cartes')]
final class CartesController extends AbstractController
{
    #[Route(name: 'app_cartes_index', methods: ['GET'])]
    public function index(CartesRepository $cartesRepository): Response
    {
        return $this->render('cartes/index.html.twig', [
            'cartes' => $cartesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cartes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $carte = new Cartes();
        $formCarte = $this->createForm(CartesType::class, $carte);
        $formCarte->handleRequest($request);

        if ($formCarte->isSubmitted() && $formCarte->isValid()) {
            $entityManager->persist($carte);
            $entityManager->flush();

            return $this->redirectToRoute('app_cartes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cartes/new.html.twig', [
            'carte' => $carte,
            'formCarte' => $formCarte,
        ]);
    }

    #[Route('/{id}', name: 'app_cartes_show', methods: ['GET'])]
    public function show(Cartes $carte): Response
    {
        return $this->render('cartes/show.html.twig', [
            'carte' => $carte,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cartes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cartes $carte, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CartesType::class, $carte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_cartes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cartes/edit.html.twig', [
            'carte' => $carte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cartes_delete', methods: ['POST'])]
    public function delete(Request $request, Cartes $carte, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$carte->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($carte);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_cartes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cartes/_delete_form.html.twig
<form method="post" action="{{ path('app_cartes_delete', {'id': carte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cartes/_form.html.twig
{{ form_start(formCarte) }}
    <div class="form-group">
        {{ form_row(formCarte.titre) }}
    </div>
    <div class="form-group" style="margin-top: 20px;">
        {{ form_row(formCarte.description) }}
    </div>
    <div class="form-group"style="margin-top: 20px;">
        {{ form_row(formCarte.date_fin_prevu) }}
    </div>
    <div class="form-group"style="margin-top: 20px;">
        {{ form_row(formCarte.date_creation) }}
    </div>
    {# <div class="form-group"style="margin-top: 20px;">
        {{ form_row(formCarte.tags) }}
    </div> #}
    <div class="form-group"style="margin-top: 20px;">
        {{ form_row(formCarte.colonnes) }}
    </div>
    {# <div class="form-group"style="margin-top: 20px;">
        {{ form_row(formCarte.users) }}
    </div> #}
    <div class="form-group"style="margin-top: 20px;">
        {{ form_row(formCarte.submit) }}
    </div>
{{ form_end(formCarte) }}

templates/cartes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cartes{% endblock %}

{% block body %}
    <h1>Edit Cartes</h1>

    {{ include('cartes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cartes_index') }}">back to list</a>

    {{ include('cartes/_delete_form.html.twig') }}
{% endblock %}

templates/cartes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cartes index{% endblock %}

{% block body %}
    <h1>Cartes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Date_creation</th>
                <th>Date_fin</th>
                <th>Date_fin_prevu</th>
                <th>Cloture</th>
                <th>Fichier</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for carte in cartes %}
            <tr>
                <td>{{ carte.id }}</td>
                <td>{{ carte.titre }}</td>
                <td>{{ carte.dateCreation ? carte.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ carte.dateFin ? carte.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ carte.dateFinPrevu ? carte.dateFinPrevu|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ carte.cloture ? 'Yes' : 'No' }}</td>
                <td>{{ carte.fichier }}</td>
                <td>{{ carte.description }}</td>
                <td>
                    <a href="{{ path('app_cartes_show', {'id': carte.id}) }}">show</a>
                    <a href="{{ path('app_cartes_edit', {'id': carte.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_cartes_new') }}">Create new</a>
{% endblock %}

templates/cartes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cartes{% endblock %}

{% block body %}
    {{ include('cartes/_form.html.twig') }}
{% endblock %}

templates/cartes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cartes{% endblock %}

{% block body %}
    <h1>Cartes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ carte.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ carte.titre }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ carte.dateCreation ? carte.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ carte.dateFin ? carte.dateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin_prevu</th>
                <td>{{ carte.dateFinPrevu ? carte.dateFinPrevu|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Cloture</th>
                <td>{{ carte.cloture ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Fichier</th>
                <td>{{ carte.fichier }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ carte.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cartes_index') }}">back to list</a>

    <a href="{{ path('app_cartes_edit', {'id': carte.id}) }}">edit</a>

    {{ include('cartes/_delete_form.html.twig') }}
{% endblock %}